---
title: "Time Series"
subtitle: "Homework 2"
author: Helen Kafka, Sven Bergmann
date: 02/28/24
output: pdf_document
---

```{r, echo = F}
library(knitr)
opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

# Problem 1

# Problem 2

## a)

```{r, warning = F, message = F}
library(TSA)
library(tseries)
```

```{r}
data(winnebago)
plot(winnebago, xlab = expression("Time"), ylab = expression("Sales"), main = expression("Time Series Plot of Winnebago"))
```

Interpretation:



## b)


```{r}
model1 <- lm(winnebago ~ time(winnebago))
summary(model1)
```
```{r}
res <- as.ts(rstandard(model1))
plot(res, xlab = expression("Time"), ylab = expression("Residuals"), main = "Plot of Residuals versus Time")
```

Interpretation:



## c)

```{r}
ln_winnebago <- log(winnebago)
plot(ln_winnebago, xlab = expression("Time"), ylab = expression("ln Sales"), main = expression("Time Series Plot of Winnebago"))
```

## d)

```{r}
model2 <- lm(ln_winnebago ~ time(ln_winnebago))
summary(model2)
```

```{r}
res2 <- as.ts(rstandard(model2))
plot(res2, xlab = expression("Time"), ylab = expression("Residuals"), main = "ln Plot of Residuals versus Time")
```